# ----------------------------
# Makefile Options
# ----------------------------

NAME ?= HDPICV
ICON ?= icon.png
DESCRIPTION ?= "High Definition Picture Viewer 5 Dev              By TLM"
COMPRESSED ?= NO
ARCHIVED ?= YES

CFLAGS ?= -Wall -Wextra -Oz
CXXFLAGS ?= -Wall -Wextra -Oz

# ----------------------------

ifndef CEDEV
$(error CEDEV environment path variable is not set)
endif

include $(CEDEV)/meta/makefile.mk