# ----------------------------
# Set NAME to the program name
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# Set COMPRESSED to "YES" to create a compressed program
# ----------------------------

NAME        ?= HDPICV
COMPRESSED  ?= NO
ICON        ?= icon.png
DESCRIPTION ?= "High Definition Picture Viewer 5 Dev              By TLM"

# ----------------------------

include $(CEDEV)/include/.makefile
